### ISSUE TITLE
你好，为什么我提取好的光流还会保存到root_path文件夹中

### ISSUE THREAD

**Issue by Evigouse** [liu-zhy/vidtools#1]

**Comment by liu-zhy** [comment]
Normally, you should assign the path for outputs by `--out_path`. It will not save the flow images into root_path unless the out_path is the same as root_path. I hope it can address your concerns.

**Comment by Evigouse** [comment]
> Normally, you should assign the path for outputs by `--out_path`. It will not save the flow images into root_path unless the out_path is the same as root_path. I hope it can address your concerns.

谢谢，已经解决，在服务器上运行即可。
